dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
all: true

packages:
  github.com/greenbone/opensight-notification-service/pkg:
    config:
      recursive: true
