// SPDX-FileCopyrightText: 2024 Greenbone AG <https://greenbone.net>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package opensight_notification_service

// THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

var Version = "0.9.2-alpha1"
