// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewOriginService creates a new instance of OriginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOriginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OriginService {
	mock := &OriginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OriginService is an autogenerated mock type for the OriginService type
type OriginService struct {
	mock.Mock
}

type OriginService_Expecter struct {
	mock *mock.Mock
}

func (_m *OriginService) EXPECT() *OriginService_Expecter {
	return &OriginService_Expecter{mock: &_m.Mock}
}

// ListOrigins provides a mock function for the type OriginService
func (_mock *OriginService) ListOrigins(ctx context.Context) ([]entities.Origin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOrigins")
	}

	var r0 []entities.Origin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Origin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Origin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Origin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OriginService_ListOrigins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrigins'
type OriginService_ListOrigins_Call struct {
	*mock.Call
}

// ListOrigins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OriginService_Expecter) ListOrigins(ctx interface{}) *OriginService_ListOrigins_Call {
	return &OriginService_ListOrigins_Call{Call: _e.mock.On("ListOrigins", ctx)}
}

func (_c *OriginService_ListOrigins_Call) Run(run func(ctx context.Context)) *OriginService_ListOrigins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OriginService_ListOrigins_Call) Return(origins []entities.Origin, err error) *OriginService_ListOrigins_Call {
	_c.Call.Return(origins, err)
	return _c
}

func (_c *OriginService_ListOrigins_Call) RunAndReturn(run func(ctx context.Context) ([]entities.Origin, error)) *OriginService_ListOrigins_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertOrigins provides a mock function for the type OriginService
func (_mock *OriginService) UpsertOrigins(ctx context.Context, serviceID string, origins []entities.Origin) error {
	ret := _mock.Called(ctx, serviceID, origins)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOrigins")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []entities.Origin) error); ok {
		r0 = returnFunc(ctx, serviceID, origins)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OriginService_UpsertOrigins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertOrigins'
type OriginService_UpsertOrigins_Call struct {
	*mock.Call
}

// UpsertOrigins is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID string
//   - origins []entities.Origin
func (_e *OriginService_Expecter) UpsertOrigins(ctx interface{}, serviceID interface{}, origins interface{}) *OriginService_UpsertOrigins_Call {
	return &OriginService_UpsertOrigins_Call{Call: _e.mock.On("UpsertOrigins", ctx, serviceID, origins)}
}

func (_c *OriginService_UpsertOrigins_Call) Run(run func(ctx context.Context, serviceID string, origins []entities.Origin)) *OriginService_UpsertOrigins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entities.Origin
		if args[2] != nil {
			arg2 = args[2].([]entities.Origin)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OriginService_UpsertOrigins_Call) Return(err error) *OriginService_UpsertOrigins_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OriginService_UpsertOrigins_Call) RunAndReturn(run func(ctx context.Context, serviceID string, origins []entities.Origin) error) *OriginService_UpsertOrigins_Call {
	_c.Call.Return(run)
	return _c
}
