// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/greenbone/opensight-golang-libraries/pkg/errorResponses"
	"github.com/greenbone/opensight-notification-service/pkg/web/errmap"
	mock "github.com/stretchr/testify/mock"
)

// NewErrorRegistry creates a new instance of ErrorRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorRegistry {
	mock := &ErrorRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ErrorRegistry is an autogenerated mock type for the ErrorRegistry type
type ErrorRegistry struct {
	mock.Mock
}

type ErrorRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorRegistry) EXPECT() *ErrorRegistry_Expecter {
	return &ErrorRegistry_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type ErrorRegistry
func (_mock *ErrorRegistry) Lookup(err error) (errmap.Result, bool) {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 errmap.Result
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(error) (errmap.Result, bool)); ok {
		return returnFunc(err)
	}
	if returnFunc, ok := ret.Get(0).(func(error) errmap.Result); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(errmap.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(error) bool); ok {
		r1 = returnFunc(err)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ErrorRegistry_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type ErrorRegistry_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - err error
func (_e *ErrorRegistry_Expecter) Lookup(err interface{}) *ErrorRegistry_Lookup_Call {
	return &ErrorRegistry_Lookup_Call{Call: _e.mock.On("Lookup", err)}
}

func (_c *ErrorRegistry_Lookup_Call) Run(run func(err error)) *ErrorRegistry_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ErrorRegistry_Lookup_Call) Return(result errmap.Result, b bool) *ErrorRegistry_Lookup_Call {
	_c.Call.Return(result, b)
	return _c
}

func (_c *ErrorRegistry_Lookup_Call) RunAndReturn(run func(err error) (errmap.Result, bool)) *ErrorRegistry_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type ErrorRegistry
func (_mock *ErrorRegistry) Register(err error, status int, response errorResponses.ErrorResponse) {
	_mock.Called(err, status, response)
	return
}

// ErrorRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type ErrorRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - err error
//   - status int
//   - response errorResponses.ErrorResponse
func (_e *ErrorRegistry_Expecter) Register(err interface{}, status interface{}, response interface{}) *ErrorRegistry_Register_Call {
	return &ErrorRegistry_Register_Call{Call: _e.mock.On("Register", err, status, response)}
}

func (_c *ErrorRegistry_Register_Call) Run(run func(err error, status int, response errorResponses.ErrorResponse)) *ErrorRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 errorResponses.ErrorResponse
		if args[2] != nil {
			arg2 = args[2].(errorResponses.ErrorResponse)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ErrorRegistry_Register_Call) Return() *ErrorRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorRegistry_Register_Call) RunAndReturn(run func(err error, status int, response errorResponses.ErrorResponse)) *ErrorRegistry_Register_Call {
	_c.Run(run)
	return _c
}
