// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewEncryptManager creates a new instance of EncryptManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptManager {
	mock := &EncryptManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EncryptManager is an autogenerated mock type for the EncryptManager type
type EncryptManager struct {
	mock.Mock
}

type EncryptManager_Expecter struct {
	mock *mock.Mock
}

func (_m *EncryptManager) EXPECT() *EncryptManager_Expecter {
	return &EncryptManager_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type EncryptManager
func (_mock *EncryptManager) Decrypt(data []byte) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncryptManager_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type EncryptManager_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - data []byte
func (_e *EncryptManager_Expecter) Decrypt(data interface{}) *EncryptManager_Decrypt_Call {
	return &EncryptManager_Decrypt_Call{Call: _e.mock.On("Decrypt", data)}
}

func (_c *EncryptManager_Decrypt_Call) Run(run func(data []byte)) *EncryptManager_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncryptManager_Decrypt_Call) Return(s string, err error) *EncryptManager_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *EncryptManager_Decrypt_Call) RunAndReturn(run func(data []byte) (string, error)) *EncryptManager_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type EncryptManager
func (_mock *EncryptManager) Encrypt(plaintext string) ([]byte, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncryptManager_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type EncryptManager_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *EncryptManager_Expecter) Encrypt(plaintext interface{}) *EncryptManager_Encrypt_Call {
	return &EncryptManager_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *EncryptManager_Encrypt_Call) Run(run func(plaintext string)) *EncryptManager_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncryptManager_Encrypt_Call) Return(bytes []byte, err error) *EncryptManager_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *EncryptManager_Encrypt_Call) RunAndReturn(run func(plaintext string) ([]byte, error)) *EncryptManager_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
