// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mock := &HealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

type HealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthService) EXPECT() *HealthService_Expecter {
	return &HealthService_Expecter{mock: &_m.Mock}
}

// Ready provides a mock function for the type HealthService
func (_mock *HealthService) Ready(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// HealthService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type HealthService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthService_Expecter) Ready(ctx interface{}) *HealthService_Ready_Call {
	return &HealthService_Ready_Call{Call: _e.mock.On("Ready", ctx)}
}

func (_c *HealthService_Ready_Call) Run(run func(ctx context.Context)) *HealthService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthService_Ready_Call) Return(b bool) *HealthService_Ready_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *HealthService_Ready_Call) RunAndReturn(run func(ctx context.Context) bool) *HealthService_Ready_Call {
	_c.Call.Return(run)
	return _c
}
