// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/request"
	mock "github.com/stretchr/testify/mock"
)

// NewMailChannelService creates a new instance of MailChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailChannelService {
	mock := &MailChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MailChannelService is an autogenerated mock type for the MailChannelService type
type MailChannelService struct {
	mock.Mock
}

type MailChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MailChannelService) EXPECT() *MailChannelService_Expecter {
	return &MailChannelService_Expecter{mock: &_m.Mock}
}

// CreateMailChannel provides a mock function for the type MailChannelService
func (_mock *MailChannelService) CreateMailChannel(ctx context.Context, channel request.MailNotificationChannelRequest) (request.MailNotificationChannelRequest, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMailChannel")
	}

	var r0 request.MailNotificationChannelRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.MailNotificationChannelRequest) (request.MailNotificationChannelRequest, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.MailNotificationChannelRequest) request.MailNotificationChannelRequest); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Get(0).(request.MailNotificationChannelRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.MailNotificationChannelRequest) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MailChannelService_CreateMailChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMailChannel'
type MailChannelService_CreateMailChannel_Call struct {
	*mock.Call
}

// CreateMailChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel request.MailNotificationChannelRequest
func (_e *MailChannelService_Expecter) CreateMailChannel(ctx interface{}, channel interface{}) *MailChannelService_CreateMailChannel_Call {
	return &MailChannelService_CreateMailChannel_Call{Call: _e.mock.On("CreateMailChannel", ctx, channel)}
}

func (_c *MailChannelService_CreateMailChannel_Call) Run(run func(ctx context.Context, channel request.MailNotificationChannelRequest)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.MailNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(request.MailNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) Return(mailNotificationChannelRequest request.MailNotificationChannelRequest, err error) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(mailNotificationChannelRequest, err)
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) RunAndReturn(run func(ctx context.Context, channel request.MailNotificationChannelRequest) (request.MailNotificationChannelRequest, error)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(run)
	return _c
}
