// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MailChannelService is an autogenerated mock type for the MailChannelService type
type MailChannelService struct {
	mock.Mock
}

type MailChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MailChannelService) EXPECT() *MailChannelService_Expecter {
	return &MailChannelService_Expecter{mock: &_m.Mock}
}

// CreateMailChannel provides a mock function with given fields: ctx, channel
func (_m *MailChannelService) CreateMailChannel(ctx context.Context, channel models.MailNotificationChannel) (models.MailNotificationChannel, error) {
	ret := _m.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMailChannel")
	}

	var r0 models.MailNotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.MailNotificationChannel) (models.MailNotificationChannel, error)); ok {
		return rf(ctx, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.MailNotificationChannel) models.MailNotificationChannel); ok {
		r0 = rf(ctx, channel)
	} else {
		r0 = ret.Get(0).(models.MailNotificationChannel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.MailNotificationChannel) error); ok {
		r1 = rf(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MailChannelService_CreateMailChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMailChannel'
type MailChannelService_CreateMailChannel_Call struct {
	*mock.Call
}

// CreateMailChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel models.MailNotificationChannel
func (_e *MailChannelService_Expecter) CreateMailChannel(ctx interface{}, channel interface{}) *MailChannelService_CreateMailChannel_Call {
	return &MailChannelService_CreateMailChannel_Call{Call: _e.mock.On("CreateMailChannel", ctx, channel)}
}

func (_c *MailChannelService_CreateMailChannel_Call) Run(run func(ctx context.Context, channel models.MailNotificationChannel)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.MailNotificationChannel))
	})
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) Return(_a0 models.MailNotificationChannel, _a1 error) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) RunAndReturn(run func(context.Context, models.MailNotificationChannel) (models.MailNotificationChannel, error)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailChannelService creates a new instance of MailChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailChannelService {
	mock := &MailChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
