// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/request"
	mock "github.com/stretchr/testify/mock"
)

// NewMattermostChannelService creates a new instance of MattermostChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMattermostChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MattermostChannelService {
	mock := &MattermostChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MattermostChannelService is an autogenerated mock type for the MattermostChannelService type
type MattermostChannelService struct {
	mock.Mock
}

type MattermostChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MattermostChannelService) EXPECT() *MattermostChannelService_Expecter {
	return &MattermostChannelService_Expecter{mock: &_m.Mock}
}

// CreateMattermostChannel provides a mock function for the type MattermostChannelService
func (_mock *MattermostChannelService) CreateMattermostChannel(ctx context.Context, channel request.MattermostNotificationChannelRequest) (request.MattermostNotificationChannelRequest, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMattermostChannel")
	}

	var r0 request.MattermostNotificationChannelRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.MattermostNotificationChannelRequest) (request.MattermostNotificationChannelRequest, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.MattermostNotificationChannelRequest) request.MattermostNotificationChannelRequest); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Get(0).(request.MattermostNotificationChannelRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.MattermostNotificationChannelRequest) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MattermostChannelService_CreateMattermostChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMattermostChannel'
type MattermostChannelService_CreateMattermostChannel_Call struct {
	*mock.Call
}

// CreateMattermostChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel request.MattermostNotificationChannelRequest
func (_e *MattermostChannelService_Expecter) CreateMattermostChannel(ctx interface{}, channel interface{}) *MattermostChannelService_CreateMattermostChannel_Call {
	return &MattermostChannelService_CreateMattermostChannel_Call{Call: _e.mock.On("CreateMattermostChannel", ctx, channel)}
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) Run(run func(ctx context.Context, channel request.MattermostNotificationChannelRequest)) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.MattermostNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(request.MattermostNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) Return(mattermostNotificationChannelRequest request.MattermostNotificationChannelRequest, err error) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Return(mattermostNotificationChannelRequest, err)
	return _c
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) RunAndReturn(run func(ctx context.Context, channel request.MattermostNotificationChannelRequest) (request.MattermostNotificationChannelRequest, error)) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Return(run)
	return _c
}
