// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationChannelService creates a new instance of NotificationChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelService {
	mock := &NotificationChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationChannelService is an autogenerated mock type for the NotificationChannelService type
type NotificationChannelService struct {
	mock.Mock
}

type NotificationChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelService) EXPECT() *NotificationChannelService_Expecter {
	return &NotificationChannelService_Expecter{mock: &_m.Mock}
}

// CheckNotificationChannelConnectivity provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) CheckNotificationChannelConnectivity(ctx context.Context, channel models.NotificationChannel) error {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CheckNotificationChannelConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) error); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelService_CheckNotificationChannelConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNotificationChannelConnectivity'
type NotificationChannelService_CheckNotificationChannelConnectivity_Call struct {
	*mock.Call
}

// CheckNotificationChannelConnectivity is a helper method to define mock.On call
//   - ctx context.Context
//   - channel models.NotificationChannel
func (_e *NotificationChannelService_Expecter) CheckNotificationChannelConnectivity(ctx interface{}, channel interface{}) *NotificationChannelService_CheckNotificationChannelConnectivity_Call {
	return &NotificationChannelService_CheckNotificationChannelConnectivity_Call{Call: _e.mock.On("CheckNotificationChannelConnectivity", ctx, channel)}
}

func (_c *NotificationChannelService_CheckNotificationChannelConnectivity_Call) Run(run func(ctx context.Context, channel models.NotificationChannel)) *NotificationChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelService_CheckNotificationChannelConnectivity_Call) Return(err error) *NotificationChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelService_CheckNotificationChannelConnectivity_Call) RunAndReturn(run func(ctx context.Context, channel models.NotificationChannel) error) *NotificationChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// CheckNotificationChannelEntityConnectivity provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) CheckNotificationChannelEntityConnectivity(ctx context.Context, id string, channel models.NotificationChannel) error {
	ret := _mock.Called(ctx, id, channel)

	if len(ret) == 0 {
		panic("no return value specified for CheckNotificationChannelEntityConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) error); ok {
		r0 = returnFunc(ctx, id, channel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNotificationChannelEntityConnectivity'
type NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call struct {
	*mock.Call
}

// CheckNotificationChannelEntityConnectivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channel models.NotificationChannel
func (_e *NotificationChannelService_Expecter) CheckNotificationChannelEntityConnectivity(ctx interface{}, id interface{}, channel interface{}) *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call {
	return &NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call{Call: _e.mock.On("CheckNotificationChannelEntityConnectivity", ctx, id, channel)}
}

func (_c *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call) Run(run func(ctx context.Context, id string, channel models.NotificationChannel)) *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call) Return(err error) *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call) RunAndReturn(run func(ctx context.Context, id string, channel models.NotificationChannel) error) *NotificationChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotificationChannel provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) CreateNotificationChannel(ctx context.Context, channelIn models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, channelIn)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, channelIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, channelIn)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, channelIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelService_CreateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotificationChannel'
type NotificationChannelService_CreateNotificationChannel_Call struct {
	*mock.Call
}

// CreateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelIn models.NotificationChannel
func (_e *NotificationChannelService_Expecter) CreateNotificationChannel(ctx interface{}, channelIn interface{}) *NotificationChannelService_CreateNotificationChannel_Call {
	return &NotificationChannelService_CreateNotificationChannel_Call{Call: _e.mock.On("CreateNotificationChannel", ctx, channelIn)}
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) Run(run func(ctx context.Context, channelIn models.NotificationChannel)) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, channelIn models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotificationChannel provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) DeleteNotificationChannel(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelService_DeleteNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationChannel'
type NotificationChannelService_DeleteNotificationChannel_Call struct {
	*mock.Call
}

// DeleteNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelService_Expecter) DeleteNotificationChannel(ctx interface{}, id interface{}) *NotificationChannelService_DeleteNotificationChannel_Call {
	return &NotificationChannelService_DeleteNotificationChannel_Call{Call: _e.mock.On("DeleteNotificationChannel", ctx, id)}
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) Return(err error) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string) error) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationChannelByIdAndType provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) GetNotificationChannelByIdAndType(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, channelType)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelByIdAndType")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, channelType)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, id, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelService_GetNotificationChannelByIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelByIdAndType'
type NotificationChannelService_GetNotificationChannelByIdAndType_Call struct {
	*mock.Call
}

// GetNotificationChannelByIdAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelType models.ChannelType
func (_e *NotificationChannelService_Expecter) GetNotificationChannelByIdAndType(ctx interface{}, id interface{}, channelType interface{}) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	return &NotificationChannelService_GetNotificationChannelByIdAndType_Call{Call: _e.mock.On("GetNotificationChannelByIdAndType", ctx, id, channelType)}
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) Run(run func(ctx context.Context, id string, channelType models.ChannelType)) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ChannelType
		if args[2] != nil {
			arg2 = args[2].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) RunAndReturn(run func(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error)) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotificationChannelsByType provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) ListNotificationChannelsByType(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error) {
	ret := _mock.Called(ctx, channelType)

	if len(ret) == 0 {
		panic("no return value specified for ListNotificationChannelsByType")
	}

	var r0 []models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) ([]models.NotificationChannel, error)); ok {
		return returnFunc(ctx, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) []models.NotificationChannel); ok {
		r0 = returnFunc(ctx, channelType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NotificationChannel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelService_ListNotificationChannelsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotificationChannelsByType'
type NotificationChannelService_ListNotificationChannelsByType_Call struct {
	*mock.Call
}

// ListNotificationChannelsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - channelType models.ChannelType
func (_e *NotificationChannelService_Expecter) ListNotificationChannelsByType(ctx interface{}, channelType interface{}) *NotificationChannelService_ListNotificationChannelsByType_Call {
	return &NotificationChannelService_ListNotificationChannelsByType_Call{Call: _e.mock.On("ListNotificationChannelsByType", ctx, channelType)}
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) Run(run func(ctx context.Context, channelType models.ChannelType)) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ChannelType
		if args[1] != nil {
			arg1 = args[1].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) Return(notificationChannels []models.NotificationChannel, err error) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Return(notificationChannels, err)
	return _c
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) RunAndReturn(run func(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error)) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationChannel provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) UpdateNotificationChannel(ctx context.Context, id string, channelIn models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, channelIn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, channelIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, channelIn)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, id, channelIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelService_UpdateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationChannel'
type NotificationChannelService_UpdateNotificationChannel_Call struct {
	*mock.Call
}

// UpdateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelIn models.NotificationChannel
func (_e *NotificationChannelService_Expecter) UpdateNotificationChannel(ctx interface{}, id interface{}, channelIn interface{}) *NotificationChannelService_UpdateNotificationChannel_Call {
	return &NotificationChannelService_UpdateNotificationChannel_Call{Call: _e.mock.On("UpdateNotificationChannel", ctx, id, channelIn)}
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) Run(run func(ctx context.Context, id string, channelIn models.NotificationChannel)) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string, channelIn models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}
