// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NotificationChannelService is an autogenerated mock type for the NotificationChannelService type
type NotificationChannelService struct {
	mock.Mock
}

type NotificationChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelService) EXPECT() *NotificationChannelService_Expecter {
	return &NotificationChannelService_Expecter{mock: &_m.Mock}
}

// CreateNotificationChannel provides a mock function with given fields: ctx, req
func (_m *NotificationChannelService) CreateNotificationChannel(ctx context.Context, req models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.NotificationChannel) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationChannelService_CreateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotificationChannel'
type NotificationChannelService_CreateNotificationChannel_Call struct {
	*mock.Call
}

// CreateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.NotificationChannel
func (_e *NotificationChannelService_Expecter) CreateNotificationChannel(ctx interface{}, req interface{}) *NotificationChannelService_CreateNotificationChannel_Call {
	return &NotificationChannelService_CreateNotificationChannel_Call{Call: _e.mock.On("CreateNotificationChannel", ctx, req)}
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) Run(run func(ctx context.Context, req models.NotificationChannel)) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.NotificationChannel))
	})
	return _c
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) Return(_a0 models.NotificationChannel, _a1 error) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationChannelService_CreateNotificationChannel_Call) RunAndReturn(run func(context.Context, models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelService_CreateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotificationChannel provides a mock function with given fields: ctx, id
func (_m *NotificationChannelService) DeleteNotificationChannel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationChannelService_DeleteNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationChannel'
type NotificationChannelService_DeleteNotificationChannel_Call struct {
	*mock.Call
}

// DeleteNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelService_Expecter) DeleteNotificationChannel(ctx interface{}, id interface{}) *NotificationChannelService_DeleteNotificationChannel_Call {
	return &NotificationChannelService_DeleteNotificationChannel_Call{Call: _e.mock.On("DeleteNotificationChannel", ctx, id)}
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) Return(_a0 error) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationChannelService_DeleteNotificationChannel_Call) RunAndReturn(run func(context.Context, string) error) *NotificationChannelService_DeleteNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotificationChannelsByType provides a mock function with given fields: ctx, channelType
func (_m *NotificationChannelService) ListNotificationChannelsByType(ctx context.Context, channelType string) ([]models.NotificationChannel, error) {
	ret := _m.Called(ctx, channelType)

	if len(ret) == 0 {
		panic("no return value specified for ListNotificationChannelsByType")
	}

	var r0 []models.NotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.NotificationChannel, error)); ok {
		return rf(ctx, channelType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.NotificationChannel); ok {
		r0 = rf(ctx, channelType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NotificationChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, channelType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationChannelService_ListNotificationChannelsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotificationChannelsByType'
type NotificationChannelService_ListNotificationChannelsByType_Call struct {
	*mock.Call
}

// ListNotificationChannelsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - channelType string
func (_e *NotificationChannelService_Expecter) ListNotificationChannelsByType(ctx interface{}, channelType interface{}) *NotificationChannelService_ListNotificationChannelsByType_Call {
	return &NotificationChannelService_ListNotificationChannelsByType_Call{Call: _e.mock.On("ListNotificationChannelsByType", ctx, channelType)}
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) Run(run func(ctx context.Context, channelType string)) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) Return(_a0 []models.NotificationChannel, _a1 error) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationChannelService_ListNotificationChannelsByType_Call) RunAndReturn(run func(context.Context, string) ([]models.NotificationChannel, error)) *NotificationChannelService_ListNotificationChannelsByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationChannel provides a mock function with given fields: ctx, id, channelIn
func (_m *NotificationChannelService) UpdateNotificationChannel(ctx context.Context, id string, channelIn models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _m.Called(ctx, id, channelIn)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return rf(ctx, id, channelIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = rf(ctx, id, channelIn)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.NotificationChannel) error); ok {
		r1 = rf(ctx, id, channelIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationChannelService_UpdateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationChannel'
type NotificationChannelService_UpdateNotificationChannel_Call struct {
	*mock.Call
}

// UpdateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelIn models.NotificationChannel
func (_e *NotificationChannelService_Expecter) UpdateNotificationChannel(ctx interface{}, id interface{}, channelIn interface{}) *NotificationChannelService_UpdateNotificationChannel_Call {
	return &NotificationChannelService_UpdateNotificationChannel_Call{Call: _e.mock.On("UpdateNotificationChannel", ctx, id, channelIn)}
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) Run(run func(ctx context.Context, id string, channelIn models.NotificationChannel)) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.NotificationChannel))
	})
	return _c
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) Return(_a0 models.NotificationChannel, _a1 error) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationChannelService_UpdateNotificationChannel_Call) RunAndReturn(run func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelService_UpdateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationChannelService creates a new instance of NotificationChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelService {
	mock := &NotificationChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
