// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/request"
	"github.com/greenbone/opensight-notification-service/pkg/response"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamsChannelService creates a new instance of TeamsChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsChannelService {
	mock := &TeamsChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamsChannelService is an autogenerated mock type for the TeamsChannelService type
type TeamsChannelService struct {
	mock.Mock
}

type TeamsChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsChannelService) EXPECT() *TeamsChannelService_Expecter {
	return &TeamsChannelService_Expecter{mock: &_m.Mock}
}

// CreateTeamsChannel provides a mock function for the type TeamsChannelService
func (_mock *TeamsChannelService) CreateTeamsChannel(ctx context.Context, channel request.TeamsNotificationChannelRequest) (response.TeamsNotificationChannelResponse, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamsChannel")
	}

	var r0 response.TeamsNotificationChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.TeamsNotificationChannelRequest) (response.TeamsNotificationChannelResponse, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, request.TeamsNotificationChannelRequest) response.TeamsNotificationChannelResponse); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Get(0).(response.TeamsNotificationChannelResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, request.TeamsNotificationChannelRequest) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamsChannelService_CreateTeamsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamsChannel'
type TeamsChannelService_CreateTeamsChannel_Call struct {
	*mock.Call
}

// CreateTeamsChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel request.TeamsNotificationChannelRequest
func (_e *TeamsChannelService_Expecter) CreateTeamsChannel(ctx interface{}, channel interface{}) *TeamsChannelService_CreateTeamsChannel_Call {
	return &TeamsChannelService_CreateTeamsChannel_Call{Call: _e.mock.On("CreateTeamsChannel", ctx, channel)}
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) Run(run func(ctx context.Context, channel request.TeamsNotificationChannelRequest)) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 request.TeamsNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(request.TeamsNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) Return(teamsNotificationChannelResponse response.TeamsNotificationChannelResponse, err error) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Return(teamsNotificationChannelResponse, err)
	return _c
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) RunAndReturn(run func(ctx context.Context, channel request.TeamsNotificationChannelRequest) (response.TeamsNotificationChannelResponse, error)) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Return(run)
	return _c
}
