// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMailService creates a new instance of MailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailService {
	mock := &MailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MailService is an autogenerated mock type for the MailService type
type MailService struct {
	mock.Mock
}

type MailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MailService) EXPECT() *MailService_Expecter {
	return &MailService_Expecter{mock: &_m.Mock}
}

// ConnectionCheck provides a mock function for the type MailService
func (_mock *MailService) ConnectionCheck(ctx context.Context, mailServer models.NotificationChannel) error {
	ret := _mock.Called(ctx, mailServer)

	if len(ret) == 0 {
		panic("no return value specified for ConnectionCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) error); ok {
		r0 = returnFunc(ctx, mailServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailService_ConnectionCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionCheck'
type MailService_ConnectionCheck_Call struct {
	*mock.Call
}

// ConnectionCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - mailServer models.NotificationChannel
func (_e *MailService_Expecter) ConnectionCheck(ctx interface{}, mailServer interface{}) *MailService_ConnectionCheck_Call {
	return &MailService_ConnectionCheck_Call{Call: _e.mock.On("ConnectionCheck", ctx, mailServer)}
}

func (_c *MailService_ConnectionCheck_Call) Run(run func(ctx context.Context, mailServer models.NotificationChannel)) *MailService_ConnectionCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MailService_ConnectionCheck_Call) Return(err error) *MailService_ConnectionCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailService_ConnectionCheck_Call) RunAndReturn(run func(ctx context.Context, mailServer models.NotificationChannel) error) *MailService_ConnectionCheck_Call {
	_c.Call.Return(run)
	return _c
}

// SendMail provides a mock function for the type MailService
func (_mock *MailService) SendMail(ctx context.Context, mailServer models.NotificationChannel, receiver string, subject string, body string) error {
	ret := _mock.Called(ctx, mailServer, receiver, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel, string, string, string) error); ok {
		r0 = returnFunc(ctx, mailServer, receiver, subject, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailService_SendMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMail'
type MailService_SendMail_Call struct {
	*mock.Call
}

// SendMail is a helper method to define mock.On call
//   - ctx context.Context
//   - mailServer models.NotificationChannel
//   - receiver string
//   - subject string
//   - body string
func (_e *MailService_Expecter) SendMail(ctx interface{}, mailServer interface{}, receiver interface{}, subject interface{}, body interface{}) *MailService_SendMail_Call {
	return &MailService_SendMail_Call{Call: _e.mock.On("SendMail", ctx, mailServer, receiver, subject, body)}
}

func (_c *MailService_SendMail_Call) Run(run func(ctx context.Context, mailServer models.NotificationChannel, receiver string, subject string, body string)) *MailService_SendMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MailService_SendMail_Call) Return(err error) *MailService_SendMail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailService_SendMail_Call) RunAndReturn(run func(ctx context.Context, mailServer models.NotificationChannel, receiver string, subject string, body string) error) *MailService_SendMail_Call {
	_c.Call.Return(run)
	return _c
}
