// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	"github.com/greenbone/opensight-notification-service/pkg/web/mailcontroller/maildto"
	mock "github.com/stretchr/testify/mock"
)

// NewMailChannelService creates a new instance of MailChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailChannelService {
	mock := &MailChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MailChannelService is an autogenerated mock type for the MailChannelService type
type MailChannelService struct {
	mock.Mock
}

type MailChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MailChannelService) EXPECT() *MailChannelService_Expecter {
	return &MailChannelService_Expecter{mock: &_m.Mock}
}

// CheckNotificationChannelConnectivity provides a mock function for the type MailChannelService
func (_mock *MailChannelService) CheckNotificationChannelConnectivity(ctx context.Context, mailServer models.NotificationChannel) error {
	ret := _mock.Called(ctx, mailServer)

	if len(ret) == 0 {
		panic("no return value specified for CheckNotificationChannelConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) error); ok {
		r0 = returnFunc(ctx, mailServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailChannelService_CheckNotificationChannelConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNotificationChannelConnectivity'
type MailChannelService_CheckNotificationChannelConnectivity_Call struct {
	*mock.Call
}

// CheckNotificationChannelConnectivity is a helper method to define mock.On call
//   - ctx context.Context
//   - mailServer models.NotificationChannel
func (_e *MailChannelService_Expecter) CheckNotificationChannelConnectivity(ctx interface{}, mailServer interface{}) *MailChannelService_CheckNotificationChannelConnectivity_Call {
	return &MailChannelService_CheckNotificationChannelConnectivity_Call{Call: _e.mock.On("CheckNotificationChannelConnectivity", ctx, mailServer)}
}

func (_c *MailChannelService_CheckNotificationChannelConnectivity_Call) Run(run func(ctx context.Context, mailServer models.NotificationChannel)) *MailChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MailChannelService_CheckNotificationChannelConnectivity_Call) Return(err error) *MailChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailChannelService_CheckNotificationChannelConnectivity_Call) RunAndReturn(run func(ctx context.Context, mailServer models.NotificationChannel) error) *MailChannelService_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// CheckNotificationChannelEntityConnectivity provides a mock function for the type MailChannelService
func (_mock *MailChannelService) CheckNotificationChannelEntityConnectivity(ctx context.Context, id string, mailServer models.NotificationChannel) error {
	ret := _mock.Called(ctx, id, mailServer)

	if len(ret) == 0 {
		panic("no return value specified for CheckNotificationChannelEntityConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) error); ok {
		r0 = returnFunc(ctx, id, mailServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailChannelService_CheckNotificationChannelEntityConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNotificationChannelEntityConnectivity'
type MailChannelService_CheckNotificationChannelEntityConnectivity_Call struct {
	*mock.Call
}

// CheckNotificationChannelEntityConnectivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - mailServer models.NotificationChannel
func (_e *MailChannelService_Expecter) CheckNotificationChannelEntityConnectivity(ctx interface{}, id interface{}, mailServer interface{}) *MailChannelService_CheckNotificationChannelEntityConnectivity_Call {
	return &MailChannelService_CheckNotificationChannelEntityConnectivity_Call{Call: _e.mock.On("CheckNotificationChannelEntityConnectivity", ctx, id, mailServer)}
}

func (_c *MailChannelService_CheckNotificationChannelEntityConnectivity_Call) Run(run func(ctx context.Context, id string, mailServer models.NotificationChannel)) *MailChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MailChannelService_CheckNotificationChannelEntityConnectivity_Call) Return(err error) *MailChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailChannelService_CheckNotificationChannelEntityConnectivity_Call) RunAndReturn(run func(ctx context.Context, id string, mailServer models.NotificationChannel) error) *MailChannelService_CheckNotificationChannelEntityConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMailChannel provides a mock function for the type MailChannelService
func (_mock *MailChannelService) CreateMailChannel(c context.Context, channel maildto.MailNotificationChannelRequest) (maildto.MailNotificationChannelResponse, error) {
	ret := _mock.Called(c, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMailChannel")
	}

	var r0 maildto.MailNotificationChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, maildto.MailNotificationChannelRequest) (maildto.MailNotificationChannelResponse, error)); ok {
		return returnFunc(c, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, maildto.MailNotificationChannelRequest) maildto.MailNotificationChannelResponse); ok {
		r0 = returnFunc(c, channel)
	} else {
		r0 = ret.Get(0).(maildto.MailNotificationChannelResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, maildto.MailNotificationChannelRequest) error); ok {
		r1 = returnFunc(c, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MailChannelService_CreateMailChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMailChannel'
type MailChannelService_CreateMailChannel_Call struct {
	*mock.Call
}

// CreateMailChannel is a helper method to define mock.On call
//   - c context.Context
//   - channel maildto.MailNotificationChannelRequest
func (_e *MailChannelService_Expecter) CreateMailChannel(c interface{}, channel interface{}) *MailChannelService_CreateMailChannel_Call {
	return &MailChannelService_CreateMailChannel_Call{Call: _e.mock.On("CreateMailChannel", c, channel)}
}

func (_c *MailChannelService_CreateMailChannel_Call) Run(run func(c context.Context, channel maildto.MailNotificationChannelRequest)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 maildto.MailNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(maildto.MailNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) Return(mailNotificationChannelResponse maildto.MailNotificationChannelResponse, err error) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(mailNotificationChannelResponse, err)
	return _c
}

func (_c *MailChannelService_CreateMailChannel_Call) RunAndReturn(run func(c context.Context, channel maildto.MailNotificationChannelRequest) (maildto.MailNotificationChannelResponse, error)) *MailChannelService_CreateMailChannel_Call {
	_c.Call.Return(run)
	return _c
}
