// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/web/mattermostcontroller/mattermostdto"
	mock "github.com/stretchr/testify/mock"
)

// NewMattermostChannelService creates a new instance of MattermostChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMattermostChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MattermostChannelService {
	mock := &MattermostChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MattermostChannelService is an autogenerated mock type for the MattermostChannelService type
type MattermostChannelService struct {
	mock.Mock
}

type MattermostChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MattermostChannelService) EXPECT() *MattermostChannelService_Expecter {
	return &MattermostChannelService_Expecter{mock: &_m.Mock}
}

// CreateMattermostChannel provides a mock function for the type MattermostChannelService
func (_mock *MattermostChannelService) CreateMattermostChannel(c context.Context, channel mattermostdto.MattermostNotificationChannelRequest) (mattermostdto.MattermostNotificationChannelResponse, error) {
	ret := _mock.Called(c, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateMattermostChannel")
	}

	var r0 mattermostdto.MattermostNotificationChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mattermostdto.MattermostNotificationChannelRequest) (mattermostdto.MattermostNotificationChannelResponse, error)); ok {
		return returnFunc(c, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mattermostdto.MattermostNotificationChannelRequest) mattermostdto.MattermostNotificationChannelResponse); ok {
		r0 = returnFunc(c, channel)
	} else {
		r0 = ret.Get(0).(mattermostdto.MattermostNotificationChannelResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mattermostdto.MattermostNotificationChannelRequest) error); ok {
		r1 = returnFunc(c, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MattermostChannelService_CreateMattermostChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMattermostChannel'
type MattermostChannelService_CreateMattermostChannel_Call struct {
	*mock.Call
}

// CreateMattermostChannel is a helper method to define mock.On call
//   - c context.Context
//   - channel mattermostdto.MattermostNotificationChannelRequest
func (_e *MattermostChannelService_Expecter) CreateMattermostChannel(c interface{}, channel interface{}) *MattermostChannelService_CreateMattermostChannel_Call {
	return &MattermostChannelService_CreateMattermostChannel_Call{Call: _e.mock.On("CreateMattermostChannel", c, channel)}
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) Run(run func(c context.Context, channel mattermostdto.MattermostNotificationChannelRequest)) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mattermostdto.MattermostNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(mattermostdto.MattermostNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) Return(mattermostNotificationChannelResponse mattermostdto.MattermostNotificationChannelResponse, err error) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Return(mattermostNotificationChannelResponse, err)
	return _c
}

func (_c *MattermostChannelService_CreateMattermostChannel_Call) RunAndReturn(run func(c context.Context, channel mattermostdto.MattermostNotificationChannelRequest) (mattermostdto.MattermostNotificationChannelResponse, error)) *MattermostChannelService_CreateMattermostChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SendMattermostTestMessage provides a mock function for the type MattermostChannelService
func (_mock *MattermostChannelService) SendMattermostTestMessage(webhookUrl string) error {
	ret := _mock.Called(webhookUrl)

	if len(ret) == 0 {
		panic("no return value specified for SendMattermostTestMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(webhookUrl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MattermostChannelService_SendMattermostTestMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMattermostTestMessage'
type MattermostChannelService_SendMattermostTestMessage_Call struct {
	*mock.Call
}

// SendMattermostTestMessage is a helper method to define mock.On call
//   - webhookUrl string
func (_e *MattermostChannelService_Expecter) SendMattermostTestMessage(webhookUrl interface{}) *MattermostChannelService_SendMattermostTestMessage_Call {
	return &MattermostChannelService_SendMattermostTestMessage_Call{Call: _e.mock.On("SendMattermostTestMessage", webhookUrl)}
}

func (_c *MattermostChannelService_SendMattermostTestMessage_Call) Run(run func(webhookUrl string)) *MattermostChannelService_SendMattermostTestMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MattermostChannelService_SendMattermostTestMessage_Call) Return(err error) *MattermostChannelService_SendMattermostTestMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MattermostChannelService_SendMattermostTestMessage_Call) RunAndReturn(run func(webhookUrl string) error) *MattermostChannelService_SendMattermostTestMessage_Call {
	_c.Call.Return(run)
	return _c
}
