// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	"github.com/greenbone/opensight-notification-service/pkg/web/mailcontroller/dtos"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationChannelServicer creates a new instance of NotificationChannelServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelServicer {
	mock := &NotificationChannelServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationChannelServicer is an autogenerated mock type for the NotificationChannelServicer type
type NotificationChannelServicer struct {
	mock.Mock
}

type NotificationChannelServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelServicer) EXPECT() *NotificationChannelServicer_Expecter {
	return &NotificationChannelServicer_Expecter{mock: &_m.Mock}
}

// CheckNotificationChannelConnectivity provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) CheckNotificationChannelConnectivity(ctx context.Context, channel dtos.CheckMailServerRequest) error {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CheckNotificationChannelConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.CheckMailServerRequest) error); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelServicer_CheckNotificationChannelConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNotificationChannelConnectivity'
type NotificationChannelServicer_CheckNotificationChannelConnectivity_Call struct {
	*mock.Call
}

// CheckNotificationChannelConnectivity is a helper method to define mock.On call
//   - ctx context.Context
//   - channel dtos.CheckMailServerRequest
func (_e *NotificationChannelServicer_Expecter) CheckNotificationChannelConnectivity(ctx interface{}, channel interface{}) *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call {
	return &NotificationChannelServicer_CheckNotificationChannelConnectivity_Call{Call: _e.mock.On("CheckNotificationChannelConnectivity", ctx, channel)}
}

func (_c *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call) Run(run func(ctx context.Context, channel dtos.CheckMailServerRequest)) *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.CheckMailServerRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.CheckMailServerRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call) Return(err error) *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call) RunAndReturn(run func(ctx context.Context, channel dtos.CheckMailServerRequest) error) *NotificationChannelServicer_CheckNotificationChannelConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNotificationChannel provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) CreateNotificationChannel(ctx context.Context, req models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelServicer_CreateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotificationChannel'
type NotificationChannelServicer_CreateNotificationChannel_Call struct {
	*mock.Call
}

// CreateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.NotificationChannel
func (_e *NotificationChannelServicer_Expecter) CreateNotificationChannel(ctx interface{}, req interface{}) *NotificationChannelServicer_CreateNotificationChannel_Call {
	return &NotificationChannelServicer_CreateNotificationChannel_Call{Call: _e.mock.On("CreateNotificationChannel", ctx, req)}
}

func (_c *NotificationChannelServicer_CreateNotificationChannel_Call) Run(run func(ctx context.Context, req models.NotificationChannel)) *NotificationChannelServicer_CreateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_CreateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelServicer_CreateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelServicer_CreateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, req models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelServicer_CreateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotificationChannel provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) DeleteNotificationChannel(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelServicer_DeleteNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationChannel'
type NotificationChannelServicer_DeleteNotificationChannel_Call struct {
	*mock.Call
}

// DeleteNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelServicer_Expecter) DeleteNotificationChannel(ctx interface{}, id interface{}) *NotificationChannelServicer_DeleteNotificationChannel_Call {
	return &NotificationChannelServicer_DeleteNotificationChannel_Call{Call: _e.mock.On("DeleteNotificationChannel", ctx, id)}
}

func (_c *NotificationChannelServicer_DeleteNotificationChannel_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelServicer_DeleteNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_DeleteNotificationChannel_Call) Return(err error) *NotificationChannelServicer_DeleteNotificationChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelServicer_DeleteNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string) error) *NotificationChannelServicer_DeleteNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationChannelByIdAndType provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) GetNotificationChannelByIdAndType(ctx context.Context, id string, channelType models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, channelType)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelByIdAndType")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, channelType)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, id, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelServicer_GetNotificationChannelByIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelByIdAndType'
type NotificationChannelServicer_GetNotificationChannelByIdAndType_Call struct {
	*mock.Call
}

// GetNotificationChannelByIdAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelType models.NotificationChannel
func (_e *NotificationChannelServicer_Expecter) GetNotificationChannelByIdAndType(ctx interface{}, id interface{}, channelType interface{}) *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call {
	return &NotificationChannelServicer_GetNotificationChannelByIdAndType_Call{Call: _e.mock.On("GetNotificationChannelByIdAndType", ctx, id, channelType)}
}

func (_c *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call) Run(run func(ctx context.Context, id string, channelType models.NotificationChannel)) *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call) RunAndReturn(run func(ctx context.Context, id string, channelType models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelServicer_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotificationChannelsByType provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) ListNotificationChannelsByType(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error) {
	ret := _mock.Called(ctx, channelType)

	if len(ret) == 0 {
		panic("no return value specified for ListNotificationChannelsByType")
	}

	var r0 []models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) ([]models.NotificationChannel, error)); ok {
		return returnFunc(ctx, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) []models.NotificationChannel); ok {
		r0 = returnFunc(ctx, channelType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NotificationChannel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelServicer_ListNotificationChannelsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotificationChannelsByType'
type NotificationChannelServicer_ListNotificationChannelsByType_Call struct {
	*mock.Call
}

// ListNotificationChannelsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - channelType models.ChannelType
func (_e *NotificationChannelServicer_Expecter) ListNotificationChannelsByType(ctx interface{}, channelType interface{}) *NotificationChannelServicer_ListNotificationChannelsByType_Call {
	return &NotificationChannelServicer_ListNotificationChannelsByType_Call{Call: _e.mock.On("ListNotificationChannelsByType", ctx, channelType)}
}

func (_c *NotificationChannelServicer_ListNotificationChannelsByType_Call) Run(run func(ctx context.Context, channelType models.ChannelType)) *NotificationChannelServicer_ListNotificationChannelsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ChannelType
		if args[1] != nil {
			arg1 = args[1].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_ListNotificationChannelsByType_Call) Return(notificationChannels []models.NotificationChannel, err error) *NotificationChannelServicer_ListNotificationChannelsByType_Call {
	_c.Call.Return(notificationChannels, err)
	return _c
}

func (_c *NotificationChannelServicer_ListNotificationChannelsByType_Call) RunAndReturn(run func(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error)) *NotificationChannelServicer_ListNotificationChannelsByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationChannel provides a mock function for the type NotificationChannelServicer
func (_mock *NotificationChannelServicer) UpdateNotificationChannel(ctx context.Context, id string, req models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelServicer_UpdateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationChannel'
type NotificationChannelServicer_UpdateNotificationChannel_Call struct {
	*mock.Call
}

// UpdateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req models.NotificationChannel
func (_e *NotificationChannelServicer_Expecter) UpdateNotificationChannel(ctx interface{}, id interface{}, req interface{}) *NotificationChannelServicer_UpdateNotificationChannel_Call {
	return &NotificationChannelServicer_UpdateNotificationChannel_Call{Call: _e.mock.On("UpdateNotificationChannel", ctx, id, req)}
}

func (_c *NotificationChannelServicer_UpdateNotificationChannel_Call) Run(run func(ctx context.Context, id string, req models.NotificationChannel)) *NotificationChannelServicer_UpdateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelServicer_UpdateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelServicer_UpdateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelServicer_UpdateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string, req models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelServicer_UpdateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}
