// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/web/teamscontroller/teamsdto"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamsChannelService creates a new instance of TeamsChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamsChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamsChannelService {
	mock := &TeamsChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamsChannelService is an autogenerated mock type for the TeamsChannelService type
type TeamsChannelService struct {
	mock.Mock
}

type TeamsChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamsChannelService) EXPECT() *TeamsChannelService_Expecter {
	return &TeamsChannelService_Expecter{mock: &_m.Mock}
}

// CreateTeamsChannel provides a mock function for the type TeamsChannelService
func (_mock *TeamsChannelService) CreateTeamsChannel(ctx context.Context, channel teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error) {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamsChannel")
	}

	var r0 teamsdto.TeamsNotificationChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error)); ok {
		return returnFunc(ctx, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, teamsdto.TeamsNotificationChannelRequest) teamsdto.TeamsNotificationChannelResponse); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Get(0).(teamsdto.TeamsNotificationChannelResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, teamsdto.TeamsNotificationChannelRequest) error); ok {
		r1 = returnFunc(ctx, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamsChannelService_CreateTeamsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeamsChannel'
type TeamsChannelService_CreateTeamsChannel_Call struct {
	*mock.Call
}

// CreateTeamsChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel teamsdto.TeamsNotificationChannelRequest
func (_e *TeamsChannelService_Expecter) CreateTeamsChannel(ctx interface{}, channel interface{}) *TeamsChannelService_CreateTeamsChannel_Call {
	return &TeamsChannelService_CreateTeamsChannel_Call{Call: _e.mock.On("CreateTeamsChannel", ctx, channel)}
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) Run(run func(ctx context.Context, channel teamsdto.TeamsNotificationChannelRequest)) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 teamsdto.TeamsNotificationChannelRequest
		if args[1] != nil {
			arg1 = args[1].(teamsdto.TeamsNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) Return(teamsNotificationChannelResponse teamsdto.TeamsNotificationChannelResponse, err error) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Return(teamsNotificationChannelResponse, err)
	return _c
}

func (_c *TeamsChannelService_CreateTeamsChannel_Call) RunAndReturn(run func(ctx context.Context, channel teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error)) *TeamsChannelService_CreateTeamsChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SendTeamsTestMessage provides a mock function for the type TeamsChannelService
func (_mock *TeamsChannelService) SendTeamsTestMessage(webhookUrl string) error {
	ret := _mock.Called(webhookUrl)

	if len(ret) == 0 {
		panic("no return value specified for SendTeamsTestMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(webhookUrl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamsChannelService_SendTeamsTestMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTeamsTestMessage'
type TeamsChannelService_SendTeamsTestMessage_Call struct {
	*mock.Call
}

// SendTeamsTestMessage is a helper method to define mock.On call
//   - webhookUrl string
func (_e *TeamsChannelService_Expecter) SendTeamsTestMessage(webhookUrl interface{}) *TeamsChannelService_SendTeamsTestMessage_Call {
	return &TeamsChannelService_SendTeamsTestMessage_Call{Call: _e.mock.On("SendTeamsTestMessage", webhookUrl)}
}

func (_c *TeamsChannelService_SendTeamsTestMessage_Call) Run(run func(webhookUrl string)) *TeamsChannelService_SendTeamsTestMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TeamsChannelService_SendTeamsTestMessage_Call) Return(err error) *TeamsChannelService_SendTeamsTestMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamsChannelService_SendTeamsTestMessage_Call) RunAndReturn(run func(webhookUrl string) error) *TeamsChannelService_SendTeamsTestMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTeamsChannel provides a mock function for the type TeamsChannelService
func (_mock *TeamsChannelService) UpdateTeamsChannel(ctx context.Context, id string, channel teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error) {
	ret := _mock.Called(ctx, id, channel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeamsChannel")
	}

	var r0 teamsdto.TeamsNotificationChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error)); ok {
		return returnFunc(ctx, id, channel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, teamsdto.TeamsNotificationChannelRequest) teamsdto.TeamsNotificationChannelResponse); ok {
		r0 = returnFunc(ctx, id, channel)
	} else {
		r0 = ret.Get(0).(teamsdto.TeamsNotificationChannelResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, teamsdto.TeamsNotificationChannelRequest) error); ok {
		r1 = returnFunc(ctx, id, channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamsChannelService_UpdateTeamsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTeamsChannel'
type TeamsChannelService_UpdateTeamsChannel_Call struct {
	*mock.Call
}

// UpdateTeamsChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channel teamsdto.TeamsNotificationChannelRequest
func (_e *TeamsChannelService_Expecter) UpdateTeamsChannel(ctx interface{}, id interface{}, channel interface{}) *TeamsChannelService_UpdateTeamsChannel_Call {
	return &TeamsChannelService_UpdateTeamsChannel_Call{Call: _e.mock.On("UpdateTeamsChannel", ctx, id, channel)}
}

func (_c *TeamsChannelService_UpdateTeamsChannel_Call) Run(run func(ctx context.Context, id string, channel teamsdto.TeamsNotificationChannelRequest)) *TeamsChannelService_UpdateTeamsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 teamsdto.TeamsNotificationChannelRequest
		if args[2] != nil {
			arg2 = args[2].(teamsdto.TeamsNotificationChannelRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamsChannelService_UpdateTeamsChannel_Call) Return(teamsNotificationChannelResponse teamsdto.TeamsNotificationChannelResponse, err error) *TeamsChannelService_UpdateTeamsChannel_Call {
	_c.Call.Return(teamsNotificationChannelResponse, err)
	return _c
}

func (_c *TeamsChannelService_UpdateTeamsChannel_Call) RunAndReturn(run func(ctx context.Context, id string, channel teamsdto.TeamsNotificationChannelRequest) (teamsdto.TeamsNotificationChannelResponse, error)) *TeamsChannelService_UpdateTeamsChannel_Call {
	_c.Call.Return(run)
	return _c
}
