// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationChannelService creates a new instance of NotificationChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelService {
	mock := &NotificationChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationChannelService is an autogenerated mock type for the NotificationChannelService type
type NotificationChannelService struct {
	mock.Mock
}

type NotificationChannelService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelService) EXPECT() *NotificationChannelService_Expecter {
	return &NotificationChannelService_Expecter{mock: &_m.Mock}
}

// GetNotificationChannelByIdAndType provides a mock function for the type NotificationChannelService
func (_mock *NotificationChannelService) GetNotificationChannelByIdAndType(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, channelType)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelByIdAndType")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, channelType)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, id, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelService_GetNotificationChannelByIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelByIdAndType'
type NotificationChannelService_GetNotificationChannelByIdAndType_Call struct {
	*mock.Call
}

// GetNotificationChannelByIdAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelType models.ChannelType
func (_e *NotificationChannelService_Expecter) GetNotificationChannelByIdAndType(ctx interface{}, id interface{}, channelType interface{}) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	return &NotificationChannelService_GetNotificationChannelByIdAndType_Call{Call: _e.mock.On("GetNotificationChannelByIdAndType", ctx, id, channelType)}
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) Run(run func(ctx context.Context, id string, channelType models.ChannelType)) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ChannelType
		if args[2] != nil {
			arg2 = args[2].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelService_GetNotificationChannelByIdAndType_Call) RunAndReturn(run func(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error)) *NotificationChannelService_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(run)
	return _c
}
