// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRuleService creates a new instance of RuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleService {
	mock := &RuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RuleService is an autogenerated mock type for the RuleService type
type RuleService struct {
	mock.Mock
}

type RuleService_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleService) EXPECT() *RuleService_Expecter {
	return &RuleService_Expecter{mock: &_m.Mock}
}

// ProcessRules provides a mock function for the type RuleService
func (_mock *RuleService) ProcessRules(ctx context.Context, notification models.Notification) ([]models.Action, error) {
	ret := _mock.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRules")
	}

	var r0 []models.Action
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Notification) ([]models.Action, error)); ok {
		return returnFunc(ctx, notification)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Notification) []models.Action); ok {
		r0 = returnFunc(ctx, notification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Action)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Notification) error); ok {
		r1 = returnFunc(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuleService_ProcessRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRules'
type RuleService_ProcessRules_Call struct {
	*mock.Call
}

// ProcessRules is a helper method to define mock.On call
//   - ctx context.Context
//   - notification models.Notification
func (_e *RuleService_Expecter) ProcessRules(ctx interface{}, notification interface{}) *RuleService_ProcessRules_Call {
	return &RuleService_ProcessRules_Call{Call: _e.mock.On("ProcessRules", ctx, notification)}
}

func (_c *RuleService_ProcessRules_Call) Run(run func(ctx context.Context, notification models.Notification)) *RuleService_ProcessRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Notification
		if args[1] != nil {
			arg1 = args[1].(models.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleService_ProcessRules_Call) Return(actions []models.Action, err error) *RuleService_ProcessRules_Call {
	_c.Call.Return(actions, err)
	return _c
}

func (_c *RuleService_ProcessRules_Call) RunAndReturn(run func(ctx context.Context, notification models.Notification) ([]models.Action, error)) *RuleService_ProcessRules_Call {
	_c.Call.Return(run)
	return _c
}
