// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWebhookService creates a new instance of WebhookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookService {
	mock := &WebhookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WebhookService is an autogenerated mock type for the WebhookService type
type WebhookService struct {
	mock.Mock
}

type WebhookService_Expecter struct {
	mock *mock.Mock
}

func (_m *WebhookService) EXPECT() *WebhookService_Expecter {
	return &WebhookService_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type WebhookService
func (_mock *WebhookService) SendMessage(webhookUrl string, message string) error {
	ret := _mock.Called(webhookUrl, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(webhookUrl, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WebhookService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type WebhookService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - webhookUrl string
//   - message string
func (_e *WebhookService_Expecter) SendMessage(webhookUrl interface{}, message interface{}) *WebhookService_SendMessage_Call {
	return &WebhookService_SendMessage_Call{Call: _e.mock.On("SendMessage", webhookUrl, message)}
}

func (_c *WebhookService_SendMessage_Call) Run(run func(webhookUrl string, message string)) *WebhookService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WebhookService_SendMessage_Call) Return(err error) *WebhookService_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WebhookService_SendMessage_Call) RunAndReturn(run func(webhookUrl string, message string) error) *WebhookService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
