// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationChannelRepository creates a new instance of NotificationChannelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelRepository {
	mock := &NotificationChannelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationChannelRepository is an autogenerated mock type for the NotificationChannelRepository type
type NotificationChannelRepository struct {
	mock.Mock
}

type NotificationChannelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelRepository) EXPECT() *NotificationChannelRepository_Expecter {
	return &NotificationChannelRepository_Expecter{mock: &_m.Mock}
}

// CreateNotificationChannel provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) CreateNotificationChannel(ctx context.Context, channelIn models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, channelIn)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, channelIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, channelIn)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, channelIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_CreateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotificationChannel'
type NotificationChannelRepository_CreateNotificationChannel_Call struct {
	*mock.Call
}

// CreateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelIn models.NotificationChannel
func (_e *NotificationChannelRepository_Expecter) CreateNotificationChannel(ctx interface{}, channelIn interface{}) *NotificationChannelRepository_CreateNotificationChannel_Call {
	return &NotificationChannelRepository_CreateNotificationChannel_Call{Call: _e.mock.On("CreateNotificationChannel", ctx, channelIn)}
}

func (_c *NotificationChannelRepository_CreateNotificationChannel_Call) Run(run func(ctx context.Context, channelIn models.NotificationChannel)) *NotificationChannelRepository_CreateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NotificationChannel
		if args[1] != nil {
			arg1 = args[1].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_CreateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelRepository_CreateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelRepository_CreateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, channelIn models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelRepository_CreateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotificationChannel provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) DeleteNotificationChannel(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotificationChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NotificationChannelRepository_DeleteNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotificationChannel'
type NotificationChannelRepository_DeleteNotificationChannel_Call struct {
	*mock.Call
}

// DeleteNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelRepository_Expecter) DeleteNotificationChannel(ctx interface{}, id interface{}) *NotificationChannelRepository_DeleteNotificationChannel_Call {
	return &NotificationChannelRepository_DeleteNotificationChannel_Call{Call: _e.mock.On("DeleteNotificationChannel", ctx, id)}
}

func (_c *NotificationChannelRepository_DeleteNotificationChannel_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelRepository_DeleteNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_DeleteNotificationChannel_Call) Return(err error) *NotificationChannelRepository_DeleteNotificationChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NotificationChannelRepository_DeleteNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string) error) *NotificationChannelRepository_DeleteNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationChannelById provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) GetNotificationChannelById(ctx context.Context, id string) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelById")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_GetNotificationChannelById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelById'
type NotificationChannelRepository_GetNotificationChannelById_Call struct {
	*mock.Call
}

// GetNotificationChannelById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelRepository_Expecter) GetNotificationChannelById(ctx interface{}, id interface{}) *NotificationChannelRepository_GetNotificationChannelById_Call {
	return &NotificationChannelRepository_GetNotificationChannelById_Call{Call: _e.mock.On("GetNotificationChannelById", ctx, id)}
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) RunAndReturn(run func(ctx context.Context, id string) (models.NotificationChannel, error)) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationChannelByIdAndType provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) GetNotificationChannelByIdAndType(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, channelType)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelByIdAndType")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.ChannelType) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, channelType)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, id, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_GetNotificationChannelByIdAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelByIdAndType'
type NotificationChannelRepository_GetNotificationChannelByIdAndType_Call struct {
	*mock.Call
}

// GetNotificationChannelByIdAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - channelType models.ChannelType
func (_e *NotificationChannelRepository_Expecter) GetNotificationChannelByIdAndType(ctx interface{}, id interface{}, channelType interface{}) *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call {
	return &NotificationChannelRepository_GetNotificationChannelByIdAndType_Call{Call: _e.mock.On("GetNotificationChannelByIdAndType", ctx, id, channelType)}
}

func (_c *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call) Run(run func(ctx context.Context, id string, channelType models.ChannelType)) *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.ChannelType
		if args[2] != nil {
			arg2 = args[2].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call) RunAndReturn(run func(ctx context.Context, id string, channelType models.ChannelType) (models.NotificationChannel, error)) *NotificationChannelRepository_GetNotificationChannelByIdAndType_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotificationChannelsByType provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) ListNotificationChannelsByType(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error) {
	ret := _mock.Called(ctx, channelType)

	if len(ret) == 0 {
		panic("no return value specified for ListNotificationChannelsByType")
	}

	var r0 []models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) ([]models.NotificationChannel, error)); ok {
		return returnFunc(ctx, channelType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.ChannelType) []models.NotificationChannel); ok {
		r0 = returnFunc(ctx, channelType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NotificationChannel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.ChannelType) error); ok {
		r1 = returnFunc(ctx, channelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_ListNotificationChannelsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotificationChannelsByType'
type NotificationChannelRepository_ListNotificationChannelsByType_Call struct {
	*mock.Call
}

// ListNotificationChannelsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - channelType models.ChannelType
func (_e *NotificationChannelRepository_Expecter) ListNotificationChannelsByType(ctx interface{}, channelType interface{}) *NotificationChannelRepository_ListNotificationChannelsByType_Call {
	return &NotificationChannelRepository_ListNotificationChannelsByType_Call{Call: _e.mock.On("ListNotificationChannelsByType", ctx, channelType)}
}

func (_c *NotificationChannelRepository_ListNotificationChannelsByType_Call) Run(run func(ctx context.Context, channelType models.ChannelType)) *NotificationChannelRepository_ListNotificationChannelsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.ChannelType
		if args[1] != nil {
			arg1 = args[1].(models.ChannelType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_ListNotificationChannelsByType_Call) Return(notificationChannels []models.NotificationChannel, err error) *NotificationChannelRepository_ListNotificationChannelsByType_Call {
	_c.Call.Return(notificationChannels, err)
	return _c
}

func (_c *NotificationChannelRepository_ListNotificationChannelsByType_Call) RunAndReturn(run func(ctx context.Context, channelType models.ChannelType) ([]models.NotificationChannel, error)) *NotificationChannelRepository_ListNotificationChannelsByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotificationChannel provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) UpdateNotificationChannel(ctx context.Context, id string, in models.NotificationChannel) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationChannel")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.NotificationChannel) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.NotificationChannel) error); ok {
		r1 = returnFunc(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_UpdateNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotificationChannel'
type NotificationChannelRepository_UpdateNotificationChannel_Call struct {
	*mock.Call
}

// UpdateNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in models.NotificationChannel
func (_e *NotificationChannelRepository_Expecter) UpdateNotificationChannel(ctx interface{}, id interface{}, in interface{}) *NotificationChannelRepository_UpdateNotificationChannel_Call {
	return &NotificationChannelRepository_UpdateNotificationChannel_Call{Call: _e.mock.On("UpdateNotificationChannel", ctx, id, in)}
}

func (_c *NotificationChannelRepository_UpdateNotificationChannel_Call) Run(run func(ctx context.Context, id string, in models.NotificationChannel)) *NotificationChannelRepository_UpdateNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.NotificationChannel
		if args[2] != nil {
			arg2 = args[2].(models.NotificationChannel)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_UpdateNotificationChannel_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelRepository_UpdateNotificationChannel_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelRepository_UpdateNotificationChannel_Call) RunAndReturn(run func(ctx context.Context, id string, in models.NotificationChannel) (models.NotificationChannel, error)) *NotificationChannelRepository_UpdateNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}
