// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-golang-libraries/pkg/query"
	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

type NotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepository) EXPECT() *NotificationRepository_Expecter {
	return &NotificationRepository_Expecter{mock: &_m.Mock}
}

// CreateNotification provides a mock function for the type NotificationRepository
func (_mock *NotificationRepository) CreateNotification(ctx context.Context, notificationIn models.Notification) (models.Notification, error) {
	ret := _mock.Called(ctx, notificationIn)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 models.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Notification) (models.Notification, error)); ok {
		return returnFunc(ctx, notificationIn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Notification) models.Notification); ok {
		r0 = returnFunc(ctx, notificationIn)
	} else {
		r0 = ret.Get(0).(models.Notification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Notification) error); ok {
		r1 = returnFunc(ctx, notificationIn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationRepository_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type NotificationRepository_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationIn models.Notification
func (_e *NotificationRepository_Expecter) CreateNotification(ctx interface{}, notificationIn interface{}) *NotificationRepository_CreateNotification_Call {
	return &NotificationRepository_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, notificationIn)}
}

func (_c *NotificationRepository_CreateNotification_Call) Run(run func(ctx context.Context, notificationIn models.Notification)) *NotificationRepository_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Notification
		if args[1] != nil {
			arg1 = args[1].(models.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepository_CreateNotification_Call) Return(notification models.Notification, err error) *NotificationRepository_CreateNotification_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *NotificationRepository_CreateNotification_Call) RunAndReturn(run func(ctx context.Context, notificationIn models.Notification) (models.Notification, error)) *NotificationRepository_CreateNotification_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotifications provides a mock function for the type NotificationRepository
func (_mock *NotificationRepository) ListNotifications(ctx context.Context, resultSelector query.ResultSelector) ([]models.Notification, uint64, error) {
	ret := _mock.Called(ctx, resultSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []models.Notification
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.ResultSelector) ([]models.Notification, uint64, error)); ok {
		return returnFunc(ctx, resultSelector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.ResultSelector) []models.Notification); ok {
		r0 = returnFunc(ctx, resultSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, query.ResultSelector) uint64); ok {
		r1 = returnFunc(ctx, resultSelector)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, query.ResultSelector) error); ok {
		r2 = returnFunc(ctx, resultSelector)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// NotificationRepository_ListNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotifications'
type NotificationRepository_ListNotifications_Call struct {
	*mock.Call
}

// ListNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - resultSelector query.ResultSelector
func (_e *NotificationRepository_Expecter) ListNotifications(ctx interface{}, resultSelector interface{}) *NotificationRepository_ListNotifications_Call {
	return &NotificationRepository_ListNotifications_Call{Call: _e.mock.On("ListNotifications", ctx, resultSelector)}
}

func (_c *NotificationRepository_ListNotifications_Call) Run(run func(ctx context.Context, resultSelector query.ResultSelector)) *NotificationRepository_ListNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.ResultSelector
		if args[1] != nil {
			arg1 = args[1].(query.ResultSelector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationRepository_ListNotifications_Call) Return(notifications []models.Notification, totalResults uint64, err error) *NotificationRepository_ListNotifications_Call {
	_c.Call.Return(notifications, totalResults, err)
	return _c
}

func (_c *NotificationRepository_ListNotifications_Call) RunAndReturn(run func(ctx context.Context, resultSelector query.ResultSelector) ([]models.Notification, uint64, error)) *NotificationRepository_ListNotifications_Call {
	_c.Call.Return(run)
	return _c
}
