// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCleaner creates a new instance of Cleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cleaner {
	mock := &Cleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cleaner is an autogenerated mock type for the Cleaner type
type Cleaner struct {
	mock.Mock
}

type Cleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *Cleaner) EXPECT() *Cleaner_Expecter {
	return &Cleaner_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type Cleaner
func (_mock *Cleaner) Cleanup() {
	_mock.Called()
	return
}

// Cleaner_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type Cleaner_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *Cleaner_Expecter) Cleanup() *Cleaner_Cleanup_Call {
	return &Cleaner_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *Cleaner_Cleanup_Call) Run(run func()) *Cleaner_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cleaner_Cleanup_Call) Return() *Cleaner_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *Cleaner_Cleanup_Call) RunAndReturn(run func()) *Cleaner_Cleanup_Call {
	_c.Run(run)
	return _c
}
