// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewValidate creates a new instance of Validate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidate(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validate {
	mock := &Validate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Validate is an autogenerated mock type for the Validate type
type Validate struct {
	mock.Mock
}

type Validate_Expecter struct {
	mock *mock.Mock
}

func (_m *Validate) EXPECT() *Validate_Expecter {
	return &Validate_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type Validate
func (_mock *Validate) Validate() models.ValidationErrors {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 models.ValidationErrors
	if returnFunc, ok := ret.Get(0).(func() models.ValidationErrors); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.ValidationErrors)
		}
	}
	return r0
}

// Validate_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Validate_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *Validate_Expecter) Validate() *Validate_Validate_Call {
	return &Validate_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *Validate_Validate_Call) Run(run func()) *Validate_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Validate_Validate_Call) Return(validationErrors models.ValidationErrors) *Validate_Validate_Call {
	_c.Call.Return(validationErrors)
	return _c
}

func (_c *Validate_Validate_Call) RunAndReturn(run func() models.ValidationErrors) *Validate_Validate_Call {
	_c.Call.Return(run)
	return _c
}
