// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewNotificationChannelRepository creates a new instance of NotificationChannelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationChannelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationChannelRepository {
	mock := &NotificationChannelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NotificationChannelRepository is an autogenerated mock type for the NotificationChannelRepository type
type NotificationChannelRepository struct {
	mock.Mock
}

type NotificationChannelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationChannelRepository) EXPECT() *NotificationChannelRepository_Expecter {
	return &NotificationChannelRepository_Expecter{mock: &_m.Mock}
}

// GetNotificationChannelById provides a mock function for the type NotificationChannelRepository
func (_mock *NotificationChannelRepository) GetNotificationChannelById(ctx context.Context, id string) (models.NotificationChannel, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationChannelById")
	}

	var r0 models.NotificationChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.NotificationChannel, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.NotificationChannel); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.NotificationChannel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NotificationChannelRepository_GetNotificationChannelById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationChannelById'
type NotificationChannelRepository_GetNotificationChannelById_Call struct {
	*mock.Call
}

// GetNotificationChannelById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *NotificationChannelRepository_Expecter) GetNotificationChannelById(ctx interface{}, id interface{}) *NotificationChannelRepository_GetNotificationChannelById_Call {
	return &NotificationChannelRepository_GetNotificationChannelById_Call{Call: _e.mock.On("GetNotificationChannelById", ctx, id)}
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) Run(run func(ctx context.Context, id string)) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) Return(notificationChannel models.NotificationChannel, err error) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Return(notificationChannel, err)
	return _c
}

func (_c *NotificationChannelRepository_GetNotificationChannelById_Call) RunAndReturn(run func(ctx context.Context, id string) (models.NotificationChannel, error)) *NotificationChannelRepository_GetNotificationChannelById_Call {
	_c.Call.Return(run)
	return _c
}
