// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewOriginRepository creates a new instance of OriginRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOriginRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OriginRepository {
	mock := &OriginRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OriginRepository is an autogenerated mock type for the OriginRepository type
type OriginRepository struct {
	mock.Mock
}

type OriginRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OriginRepository) EXPECT() *OriginRepository_Expecter {
	return &OriginRepository_Expecter{mock: &_m.Mock}
}

// ListOrigins provides a mock function for the type OriginRepository
func (_mock *OriginRepository) ListOrigins(ctx context.Context) ([]entities.Origin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOrigins")
	}

	var r0 []entities.Origin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Origin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Origin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Origin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OriginRepository_ListOrigins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrigins'
type OriginRepository_ListOrigins_Call struct {
	*mock.Call
}

// ListOrigins is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OriginRepository_Expecter) ListOrigins(ctx interface{}) *OriginRepository_ListOrigins_Call {
	return &OriginRepository_ListOrigins_Call{Call: _e.mock.On("ListOrigins", ctx)}
}

func (_c *OriginRepository_ListOrigins_Call) Run(run func(ctx context.Context)) *OriginRepository_ListOrigins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OriginRepository_ListOrigins_Call) Return(origins []entities.Origin, err error) *OriginRepository_ListOrigins_Call {
	_c.Call.Return(origins, err)
	return _c
}

func (_c *OriginRepository_ListOrigins_Call) RunAndReturn(run func(ctx context.Context) ([]entities.Origin, error)) *OriginRepository_ListOrigins_Call {
	_c.Call.Return(run)
	return _c
}
