// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/greenbone/opensight-notification-service/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewRuleRepository creates a new instance of RuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleRepository {
	mock := &RuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RuleRepository is an autogenerated mock type for the RuleRepository type
type RuleRepository struct {
	mock.Mock
}

type RuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleRepository) EXPECT() *RuleRepository_Expecter {
	return &RuleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RuleRepository
func (_mock *RuleRepository) Create(ctx context.Context, rule models.Rule) (models.Rule, error) {
	ret := _mock.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Rule) (models.Rule, error)); ok {
		return returnFunc(ctx, rule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Rule) models.Rule); ok {
		r0 = returnFunc(ctx, rule)
	} else {
		r0 = ret.Get(0).(models.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Rule) error); ok {
		r1 = returnFunc(ctx, rule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RuleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rule models.Rule
func (_e *RuleRepository_Expecter) Create(ctx interface{}, rule interface{}) *RuleRepository_Create_Call {
	return &RuleRepository_Create_Call{Call: _e.mock.On("Create", ctx, rule)}
}

func (_c *RuleRepository_Create_Call) Run(run func(ctx context.Context, rule models.Rule)) *RuleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Rule
		if args[1] != nil {
			arg1 = args[1].(models.Rule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleRepository_Create_Call) Return(rule1 models.Rule, err error) *RuleRepository_Create_Call {
	_c.Call.Return(rule1, err)
	return _c
}

func (_c *RuleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, rule models.Rule) (models.Rule, error)) *RuleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type RuleRepository
func (_mock *RuleRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RuleRepository_Expecter) Delete(ctx interface{}, id interface{}) *RuleRepository_Delete_Call {
	return &RuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RuleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *RuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleRepository_Delete_Call) Return(err error) *RuleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RuleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *RuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type RuleRepository
func (_mock *RuleRepository) Get(ctx context.Context, id string) (models.Rule, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Rule, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Rule); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuleRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RuleRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RuleRepository_Expecter) Get(ctx interface{}, id interface{}) *RuleRepository_Get_Call {
	return &RuleRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *RuleRepository_Get_Call) Run(run func(ctx context.Context, id string)) *RuleRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleRepository_Get_Call) Return(rule models.Rule, err error) *RuleRepository_Get_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *RuleRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (models.Rule, error)) *RuleRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RuleRepository
func (_mock *RuleRepository) List(ctx context.Context) ([]models.Rule, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Rule, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Rule); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RuleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RuleRepository_Expecter) List(ctx interface{}) *RuleRepository_List_Call {
	return &RuleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *RuleRepository_List_Call) Run(run func(ctx context.Context)) *RuleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RuleRepository_List_Call) Return(rules []models.Rule, err error) *RuleRepository_List_Call {
	_c.Call.Return(rules, err)
	return _c
}

func (_c *RuleRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]models.Rule, error)) *RuleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type RuleRepository
func (_mock *RuleRepository) Update(ctx context.Context, id string, rule models.Rule) (models.Rule, error) {
	ret := _mock.Called(ctx, id, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.Rule) (models.Rule, error)); ok {
		return returnFunc(ctx, id, rule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.Rule) models.Rule); ok {
		r0 = returnFunc(ctx, id, rule)
	} else {
		r0 = ret.Get(0).(models.Rule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.Rule) error); ok {
		r1 = returnFunc(ctx, id, rule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rule models.Rule
func (_e *RuleRepository_Expecter) Update(ctx interface{}, id interface{}, rule interface{}) *RuleRepository_Update_Call {
	return &RuleRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, rule)}
}

func (_c *RuleRepository_Update_Call) Run(run func(ctx context.Context, id string, rule models.Rule)) *RuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.Rule
		if args[2] != nil {
			arg2 = args[2].(models.Rule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RuleRepository_Update_Call) Return(rule1 models.Rule, err error) *RuleRepository_Update_Call {
	_c.Call.Return(rule1, err)
	return _c
}

func (_c *RuleRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id string, rule models.Rule) (models.Rule, error)) *RuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
