definitions:
  dtos.VersionResponseDto:
    properties:
      version:
        example: 0.0.1-alpha1-dev1
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: HTTP API for live probes
  license:
    name: AGPL-3.0-or-later
  title: Health API
  version: "1.0"
paths:
  /api/notification-service/version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.VersionResponseDto'
      summary: Read API version
      tags:
      - health
  /health/alive:
    get:
      description: Endpoint for 'alive' health probes
      responses:
        "200":
          description: Alive
      summary: Service health status Alive
      tags:
      - health
  /health/ready:
    get:
      description: Indicates if the service is ready to serve traffic
      responses:
        "200":
          description: Ready
        "404":
          description: Not ready
      summary: Service health status Ready
      tags:
      - health
  /health/started:
    get:
      description: Endpoint for 'started' health probes
      responses:
        "200":
          description: Started
      summary: Service health status Started
      tags:
      - health
swagger: "2.0"
