// Package health Code generated by swaggo/swag. DO NOT EDIT
package health

import "github.com/swaggo/swag"

const docTemplatehealth = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "AGPL-3.0-or-later"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/notification-service/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Read API version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.VersionResponseDto"
                        }
                    }
                }
            }
        },
        "/health/alive": {
            "get": {
                "description": "Endpoint for 'alive' health probes",
                "tags": [
                    "health"
                ],
                "summary": "Service health status Alive",
                "responses": {
                    "200": {
                        "description": "Alive"
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Indicates if the service is ready to serve traffic",
                "tags": [
                    "health"
                ],
                "summary": "Service health status Ready",
                "responses": {
                    "200": {
                        "description": "Ready"
                    },
                    "404": {
                        "description": "Not ready"
                    }
                }
            }
        },
        "/health/started": {
            "get": {
                "description": "Endpoint for 'started' health probes",
                "tags": [
                    "health"
                ],
                "summary": "Service health status Started",
                "responses": {
                    "200": {
                        "description": "Started"
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.VersionResponseDto": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "example": "0.0.1-alpha1-dev1"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfohealth holds exported Swagger Info so clients can modify it
var SwaggerInfohealth = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Health API",
	Description:      "HTTP API for live probes",
	InfoInstanceName: "health",
	SwaggerTemplate:  docTemplatehealth,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfohealth.InstanceName(), SwaggerInfohealth)
}
