name: govulncheck

# check for vulnerabilities using `govulncheck`, compared to dependabot it only alerts if the affected code is actually called

on:
  pull_request: # make sure there is no vulnerability added with a new feature
  schedule: # check if used code of existing dependencies is vulnerable
    - cron: '37 4 * * *' # daily 4:37h
  workflow_dispatch: # on demand

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'
          check-latest: true

      - name: govulncheck
        run: make govulncheck
